[env:illy-bridge]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf

monitor_speed = 115200
upload_speed = 921600

build_flags =
    -DCONFIG_ESP_WIFI_CSI_ENABLED=1
    -DCONFIG_ESP32S3_DEFAULT_CPU_FREQ_240=1
    -DCONFIG_MBEDTLS_TLS_CLIENT_ONLY=1

board_build.partitions = default_16MB.csv
